name: node template project

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
      - name: list files
        run: ls -a
