name: node template project

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
      - name: Checkout
        uses: actions/checkout@v4
      - name: list files
        run: ls -a
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: install dependencies
        run: npm install
